# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blue Bird Technologies
description: Blue Bird helps people with mental disorders gain control over their feelings in everyday life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blue-bird-tech.com"

# Build settings
markdown: kramdown

highlighter: rouge
